# Generated by Django 5.1 on 2024-08-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourite_movies',
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_movies',
            field=models.ManyToManyField(related_name='fav', to='personas.movie'),
        ),
    ]
